repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v2.6.2"
    hooks:
      - id: prettier
        additional_dependencies:
          - prettier@2.6.2

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: "v8.12.0"
    hooks:
      - id: eslint
        additional_dependencies:
          - eslint@8.12.0
          - eslint-config-prettier@8.5.0
          - eslint-plugin-react@7.29.4
