name: release-test
on:
  pull_request_target:
    types:
      - "opened"
      - "reopened"
    branches:
      - "alpha"
      - "beta"
      - "release"
jobs:
  release-dry-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Build package
        run: npm ci
      - name: Install semantic-release
        run: |
          npm install --no-package-lock --no-save \
              @semantic-release/commit-analyzer \
              @semantic-release/release-notes-generator \
              @semantic-release/github
      - name: Release dry run
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release --debug --dryRun
