name: release
on:
  push:
    branches:
      - "alpha"
      - "beta"
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [12, 14, 16, 17, 18]
    steps:
      - uses: actions/checkout@v3
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm run clean
      - run: |
          npm install
          npx eslint .
          npm run build
      - run: npm run lint
      - run: npm run test

  release:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install semantic-release
        run: |
          npm install --no-package-lock --no-save \
              @semantic-release/commit-analyzer \
              @semantic-release/release-notes-generator \
              @semantic-release/github \
              @semantic-release/git
      - name: Release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GH_BOT_ACCESS_TOKEN }}
        run: npx semantic-release --debug
