name: java-ci

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'npm'
      - name: Install Dependencies
        run: |
          npm install
      - run: npm run clean
      - run: npm run update_api
      - run: npm run protoc
      - run: npm run lint
      - run: npm run build
      - run: npm run test
